name: Scheduled build and deploy docs to github pages
on:
  schedule:
    - cron:  '*/10 7-17 * * 1-5'
  #- workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main 
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Deploy
        run: | 
          mkdocs gh-deploy
